name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper-microservice
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: scraper-microservice/requirements.txt

      - name: Authenticate to Google Cloud (ADC for tests)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_default_credentials: true

      - name: Set GOOGLE_CLOUD_PROJECT
        run: echo "GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT }}" >> $GITHUB_ENV

      - name: Install deps (Makefile)
        run: make deps

      - name: Run tests
        env:
          PYTHONPATH: .
        run: make test

      - name: Lint
        run: make lint

      - name: Format
        run: make format

      - name: Check
        run: make check

  deploy:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper-microservice
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Ensure App Engine app exists
        run: |
          gcloud app describe || gcloud app create --region="${{ secrets.GCP_APP_REGION }}"

      - name: Create app.yaml for App Engine (standard Python 3.12)
        run: |
          cat > app.yaml << 'EOF'
          runtime: python312
          entrypoint: gunicorn -w 1 -k gthread -b :$PORT wsgi:app
          automatic_scaling:
            min_instances: 0
            max_instances: 1
          readiness_check:
            path: "/_ah/health"
            check_interval_sec: 10
            timeout_sec: 4
            failure_threshold: 3
            success_threshold: 2
            app_start_timeout_sec: 900

          liveness_check:
            path: "/_ah/health"
            check_interval_sec: 30
            timeout_sec: 4
            failure_threshold: 5
          env_variables:
            REDDIT_CLIENT_ID: "${{ secrets.REDDIT_CLIENT_ID }}"
            REDDIT_CLIENT_SECRET: "${{ secrets.REDDIT_CLIENT_SECRET }}"
            REDDIT_USER_AGENT: "nba scrape agent"
          EOF

      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet --project="${{ secrets.GCP_PROJECT }}"
